### ISSUE TITLE
test.json images names do not correspond with the provided filenames

### ISSUE THREAD

**Issue by miquel-espinosa** [anishmadan23/foundational_fsod#1]
Hi.
In the github repository, you provide a link to download the `test_set.json` file.
But the file_names for the images found int the test_set json file do not correspond with the filenames provided in the test split in the huggingface [link](https://huggingface.co/anishmadan23/foundational_fsod/blob/main/foundation_fsod_challenge/test_data/nuimages_fsod_test_images.tar).

For example:
- in the `test_set.json` we can see file_names such as `samples/CAM_FRONT/n010-2018-07-03-11-06-43+0800__CAM_FRONT__1530587851512488.jpg`
- but in the competition [metadata](https://huggingface.co/anishmadan23/foundational_fsod/blob/main/foundation_fsod_challenge/test_data/nuimages_fsod_test.json) the naming for the images is just `1.jpg`, etc. 

So, now that the challenge is over, I would appreciate the authors could provide the correct names for the images, so that we can test accuracy on the test set with annotations.

Thanks

**Comment by miquel-espinosa** [comment]
Okay, now I realise that both images in [github](https://huggingface.co/anishmadan23/foundational_fsod/blob/main/nuimages_coco_fmt/annotations/test_set.json)  and [metadata](https://huggingface.co/anishmadan23/foundational_fsod/blob/main/foundation_fsod_challenge/test_data/nuimages_fsod_test.json) share the same `'image_id'`, so one can very easily merge both jsons into a single one with a python script so that the final json contains the correct paths and the annotations for the test set.

**Comment by anishmadan23** [comment]
Yes, I had renamed the filenames initially for the challenge, but you can just access the [test_set.json link](https://huggingface.co/anishmadan23/foundational_fsod/blob/main/nuimages_coco_fmt/annotations/test_set.json) for all information about filenames and image_ids. Also yes, one could easily map the 2 files according to image_ids.
